package co.unicauca.restaurant.client.presentation;

import co.unicauca.restaurant.client.access.Factory;
import co.unicauca.restaurant.client.access.IMainDishAccess;
import co.unicauca.restaurant.client.domain.services.MainDishService;
import co.unicauca.restaurant.client.infra.Messages;
import static co.unicauca.restaurant.client.infra.Messages.successMessage;
import co.unicauca.restaurant.commons.domain.MainDish;

/**
 * Crea una jframe para crear un usuario
 * @author DANIEL NAVIA-LUIS ARROYO
 */
public class GUICreateDish extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUICreateDishe2
     */
    public GUICreateDish() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnNorte = new javax.swing.JPanel();
        jPnSur = new javax.swing.JPanel();
        jBtnAgregar = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jPnCentro = new javax.swing.JPanel();
        jLbIdPlato = new javax.swing.JLabel();
        jTxfId = new javax.swing.JTextField();
        jLbNombre = new javax.swing.JLabel();
        jTxfNombre = new javax.swing.JTextField();
        jLbPrecio = new javax.swing.JLabel();
        JTxfPrecio = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Crear Plato");
        setPreferredSize(new java.awt.Dimension(495, 230));

        jPnNorte.setBackground(new java.awt.Color(204, 204, 204));
        jPnNorte.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnNorte.setPreferredSize(new java.awt.Dimension(450, 50));

        javax.swing.GroupLayout jPnNorteLayout = new javax.swing.GroupLayout(jPnNorte);
        jPnNorte.setLayout(jPnNorteLayout);
        jPnNorteLayout.setHorizontalGroup(
            jPnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
        );
        jPnNorteLayout.setVerticalGroup(
            jPnNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        getContentPane().add(jPnNorte, java.awt.BorderLayout.PAGE_START);

        jPnSur.setBackground(new java.awt.Color(204, 204, 204));
        jPnSur.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPnSur.setPreferredSize(new java.awt.Dimension(450, 50));

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });
        jPnSur.add(jBtnAgregar);

        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });
        jPnSur.add(jBtnCancelar);

        getContentPane().add(jPnSur, java.awt.BorderLayout.PAGE_END);

        jPnCentro.setLayout(new java.awt.GridLayout(3, 2));

        jLbIdPlato.setBackground(new java.awt.Color(255, 255, 255));
        jLbIdPlato.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbIdPlato.setText("Id:");
        jPnCentro.add(jLbIdPlato);

        jTxfId.setToolTipText("txt_id");
        jPnCentro.add(jTxfId);
        jTxfId.getAccessibleContext().setAccessibleName("");

        jLbNombre.setBackground(new java.awt.Color(255, 255, 255));
        jLbNombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbNombre.setText("Nombre:");
        jPnCentro.add(jLbNombre);
        jPnCentro.add(jTxfNombre);

        jLbPrecio.setBackground(new java.awt.Color(255, 255, 255));
        jLbPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLbPrecio.setText("Precio:");
        jPnCentro.add(jLbPrecio);
        jPnCentro.add(JTxfPrecio);

        getContentPane().add(jPnCentro, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Boton para cancelar la creacion de un plato
     *
     * @param evt Evento para crear un plato
     */
    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed

        this.doDefaultCloseAction();

    }//GEN-LAST:event_jBtnCancelarActionPerformed

    /**
     * Boton encargado de crear un plato y guardarlo en la base de datos
     *
     * @param evt Evento del boton
     */
    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        IMainDishAccess service = Factory.getInstance().getMainDishService();
        // Inyecta la dependencia

        String nombre = jTxfNombre.getText();
        String id = jTxfId.getText().trim();
        String precio = JTxfPrecio.getText();

        if (id.equals("") || nombre.equals("") || precio.equals("")) {
            jTxfId.requestFocus();
            Messages.warningMessage("ERROR AL CREAR PLATO: \nCampos vacios", "Warning");
            return;
        }

        Double cost;
        cost = Double.parseDouble(precio);
        MainDishService maindishService = new MainDishService(service);
        MainDish maindish = new MainDish();
        maindish.setId_mainDish(jTxfId.getText());
        maindish.setNameDish(jTxfNombre.getText());
        maindish.setDishPrice(cost);

        try {
            String response = maindishService.createMainDish(maindish);
            if(response.equals(id)){
                successMessage("Plato agregado con éxito.", "Atención");
            }else{
                Messages.warningMessage("el planto no pudo ser agregado", "Warning");
            }
            clearControls();
            jTxfId.setText("");

        } catch (Exception ex) {
            successMessage(ex.getMessage(), "Atención");
        }
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    /**
     * Metodo que muestra los datos en el formulario
     *
     * @param maindish Plato que contiene los datos a mostrar
     */
    private void showData(MainDish maindish) {

        jTxfId.setText(maindish.getId_mainDish());
        jTxfNombre.setText(maindish.getNameDish());
        JTxfPrecio.setText(String.valueOf(maindish.getDishPrice()));

    }

    /**
     * Limpia los controlles del formulario
     */
    public void clearControls() {
        jTxfId.setText("");
        jTxfNombre.setText("");
        JTxfPrecio.setText("");

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxfPrecio;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JLabel jLbIdPlato;
    private javax.swing.JLabel jLbNombre;
    private javax.swing.JLabel jLbPrecio;
    private javax.swing.JPanel jPnCentro;
    private javax.swing.JPanel jPnNorte;
    private javax.swing.JPanel jPnSur;
    private javax.swing.JTextField jTxfId;
    private javax.swing.JTextField jTxfNombre;
    // End of variables declaration//GEN-END:variables
}
